# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 10:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lampe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('hauteur', models.PositiveIntegerField(blank=True, null=True)),
                ('largeur_socle', models.PositiveIntegerField(blank=True, null=True)),
                ('diametre', models.PositiveIntegerField(blank=True, null=True)),
                ('materiaux', models.CharField(blank=True, max_length=100, null=True)),
                ('ampoule', models.CharField(blank=True, max_length=100, null=True)),
                ('cable', models.CharField(blank=True, max_length=100, null=True)),
                ('electrification', models.CharField(blank=True, max_length=100, null=True)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('slug', models.SlugField(default='', help_text='mettre un slug unique pour cette lampe', max_length=64, verbose_name='slug')),
                ('groupe', models.ManyToManyField(related_name='lampes', to='galerie_cms_integration.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='LampeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lampe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galerie_cms_integration.Lampe')),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('geocodeAdresse', models.CharField(blank=True, max_length=200, null=True)),
                ('geolocalisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='lampe',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localisation', to='galerie_cms_integration.Localisation'),
        ),
    ]
