# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galerie_cms_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localisation',
            name='geolocalisation',
        ),
    ]
